
create table CLIENTE
( 
	CPF			BIGINT,
	NOME		VARCHAR(255)		NOT NULL,
	USUARIO		VARCHAR(50)		NOT NULL,
	ENDERECO	VARCHAR(255)		NOT NULL,
	TELEFONE	VARCHAR(15)		NOT NULL,
	EMAIL		VARCHAR(100)		NOT NULL,
	DATA_NASC	DATE			NOT NULL

	CONSTRAINT PK_CLIENTE_CPF PRIMARY KEY (CPF)

)

create table VENDEDOR
( 
	
	CPF			BIGINT						,
	NOME		VARCHAR(40)			NOT NULL,
	USUARIO		VARCHAR(40)			NOT NULL,
	ENDERECO	VARCHAR(40)			NOT NULL,
	TELEFONE	VARCHAR(15)			NOT NULL,
	EMAIL		VARCHAR(40)			NOT NULL,
	DATA_NASC	DATE				NOT NULL,

	CONSTRAINT PK_VENDEDOR_CPF PRIMARY KEY (CPF)

)

create table CATEGORIA
( 
	ID_CATEGORIA	INT		IDENTITY			,
	NOME			VARCHAR(255)			NOT NULL

	CONSTRAINT PK_CATEGORIA_ID_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
)


create table LOJA
( 
	ID_LOJA			INT		IDENTITY			,
	CPF_VENDEDOR	BIGINT				NOT NULL,
	NOME_LOJA		VARCHAR(255)		NOT NULL,
	DESCRICAO		VARCHAR(500)		NOT NULL,
	LOGO			VARBINARY(MAX)		NULL	,
	ENDERECO		VARCHAR(255)		NOT NULL,
	HORARIO_FUNC	DATE				NOT NULL,	
	NOTA			INT							,

	CONSTRAINT PK_LOJA_ID_LOJA		PRIMARY KEY (ID_LOJA),
	CONSTRAINT FK_LOJA_CPF_VENDEDOR FOREIGN KEY (CPF_VENDEDOR) REFERENCES VENDEDOR(CPF)

)

create table PRODUTO
(
	ID_PRODUTO		INT		IDENTITY			,
	NOME			VARCHAR(40)			NOT NULL,
	DESCRICAO		VARCHAR(40)			NOT NULL,
	IMAGEM			IMAGE						,
	QTD_PRODUTO		INT					NOT NULL,
	ID_CATEGORIA	INT					NOT NULL,
	ID_LOJA			INT					NOT NULL,
	VALOR			MONEY				NOT NULL,

	CONSTRAINT PK_PRODUTO_ID_PRODUTO	PRIMARY KEY (ID_PRODUTO),
	CONSTRAINT FK_PRODUTO_ID_CATEGORIA	FOREIGN KEY (ID_CATEGORIA)	REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT FK_PRODUTO_ID_LOJA		FOREIGN KEY (ID_LOJA)		REFERENCES LOJA(ID_LOJA)
)



create table ENTREGADOR
(
	ID_ENTREGADOR	INT			IDENTITY,
	CPF_ENTREGADOR	BIGINT		NOT NULL,
	NOME			VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,

	CONSTRAINT PK_ENTREGADOR_ID_ENTREGADOR	PRIMARY KEY (ID_ENTREGADOR),


)



create table PEDIDO
(
	ID_PEDIDO		INT		IDENTITY			,
	ID_PRODUTO		INT					NOT NULL,
	NOME_PRODUTO	VARCHAR(40)			NOT NULL,
	VALOR_PRODUTO	MONEY				NOT NULL,
	TOTAL			BIGINT				NOT NULL,
	STATUS_PEDIDO	VARCHAR(40)			NOT NULL,
	DATA_PEDIDO		DATE				NOT NULL,
	CPF_CLIENTE		BIGINT				NOT NULL,
	OBSERVACAO		VARCHAR(100)		NOT NULL,
	PAGAMENTO		VARCHAR(20)			NOT NULL,
	DESCONTO		MONEY				NOT NULL,
	ID_ENTREGADOR	INT					NOT NULL,

	CONSTRAINT PK_PEDIDO_ID_PEDIDO		PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_ID_PRODUTO		FOREIGN KEY (ID_PRODUTO)	REFERENCES PRODUTO(ID_PRODUTO),
	CONSTRAINT FK_PEDIDO_CPF_CLIENTE	FOREIGN KEY (CPF_CLIENTE)	REFERENCES CLIENTE(CPF),
	CONSTRAINT FK_PEDIDO_ID_ENTREGADOR	FOREIGN KEY (ID_ENTREGADOR)	REFERENCES ENTREGADOR(ID_ENTREGADOR)

)





DROP DATABASE ToComFome
CREATE DATABASE ToComFome
select * from LOJA
select * from ENTREGADOR
select * from CATEGORIA
select * from CLIENTE
select * from PEDIDO
select * from PRODUTO
select * from VENDEDOR



/* 

Alterei as seguintes tabelas: Categoria, Cliente, Entregador e Loja.

Falta refazer as seguintes tabelas: Pedido, Produto e Vendedor.

*/