
CREATE TABLE CLIENTE
(
	CPF			BIGINT			IDENTITY,
	NOME		VARCHAR(40)		NOT NULL,
	USUARIO		VARCHAR(40)		NOT NULL,
	ENDERECO	VARCHAR(40)		NOT NULL,
	TELEFONE	VARCHAR(20)		NOT NULL,
	EMAIL		VARCHAR(40)		NOT NULL,
	DATA_NASC	DATE			NOT NULL

	CONSTRAINT	PK_TB_CLIENTE_CPF		PRIMARY KEY (CPF)
)
GO
CREATE TABLE VENDEDOR
(
	CPF				BIGINT			IDENTITY,
	ID_LOJA			INT				NOT NULL,
	NOME			VARCHAR(40)		NOT NULL,
	USUARIO			VARCHAR(40)		NOT NULL,
	TELEFONE		VARCHAR(20)		NOT NULL,
	EMAIL			VARCHAR(40)		NOT NULL,
	DATA_NASC		DATE			NOT NULL
	
	CONSTRAINT	PK_TB_VENDEDOR_CPF	   PRIMARY KEY (CPF)
)
GO
CREATE TABLE CATEGORIA
(
	ID_CATEGORIA	INT				IDENTITY,
	NOME			VARCHAR(40)		NOT NULL

	CONSTRAINT	PK_TB_CATEGORIA_ID_CATEGORIA	   PRIMARY KEY (ID_CATEGORIA)
)

CREATE TABLE ESTOQUE
(
	ID_ESTOQUE		INT				IDENTITY,
	PRODUTO			BIGINT			NOT NULL,
	QTD_PRODUTO		BIGINT			NOT NULL,
	ID_LOJA			INT				

	CONSTRAINT	PK_TB_ESTOQUE_ID_ESTOQUE	   PRIMARY KEY (ID_ESTOQUE)
)
GO
CREATE TABLE LOJA
(
	ID_LOJA			INT				IDENTITY,
	CPF_VENDEDOR	BIGINT			NOT NULL,
	ID_ESTOQUE		INT				NOT NULL,
	NOME			VARCHAR(40)		NOT NULL,
	DESCRICAO		VARCHAR(40)		NOT NULL,
	LOGO			IMAGE					,
	ENDERECO		VARCHAR(40)		NOT NULL,
	HORARIO_FUNC	DATE			NOT NULL,
	NOTA			INT						,			

	CONSTRAINT	PK_TB_LOJA_ID_LOJA	   PRIMARY KEY (ID_LOJA),
	CONSTRAINT	FK_TB_LOJA_ID_ESTOQUE	   FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE),
	CONSTRAINT	FK_TB_LOJA_CPF_VENDEDOR   FOREIGN KEY (CPF_VENDEDOR) REFERENCES VENDEDOR(CPF)
)
GO
CREATE TABLE PRODUTO
(
	ID_PRODUTO		INT				IDENTITY,
	NOME			VARCHAR(40)		NOT NULL,
	DESCRICAO		VARCHAR(40)		NOT NULL,
	IMAGEM			IMAGE					,
	QTD_PRODUTO		BIGINT			NOT NULL,
	ID_CATEGORIA	INT						,
	ID_LOJA			INT						,
	VALOR			MONEY			NOT NULL

	CONSTRAINT	PK_TB_PRODUTO_ID_PRODUTO	   PRIMARY KEY (ID_PRODUTO),
	CONSTRAINT	FK_TB_PRODUTO_ID_CATEGORIA	   FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT	FK_TB_PRODUTO_ID_LOJA		   FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID_LOJA)
)
GO
CREATE TABLE PEDIDO
(
	ID_PEDIDO		INT				IDENTITY,
	ID_PRODUTO		INT						,
	NOME_PRODUTO	VARCHAR(40)		NOT NULL,
	VALOR_PRODUTO	MONEY			NOT NULL,
	TOTAL			BIGINT			NOT NULL,
	STATUS_PEDIDO	VARCHAR(20)		NOT NULL,
	ENTREGUE		VARCHAR(10)		NOT NULL,
	DATA_PEDIDO		DATE			NOT NULL,
	CPF				BIGINT			NOT NULL,
	OBSERVACAO		VARCHAR(40)				,
	PAGAMENTO		VARCHAR(20)		NOT NULL,
	DESCONTO		MONEY								
	
	CONSTRAINT	PK_TB_PEDIDO_ID_PEDIDO	   PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT	FK_TB_PEDIDO_ID_PRODUTO	   FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	CONSTRAINT	FK_TB_PEDIDO_CPF_CLIENTE   FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
)
GO
CREATE TABLE ENTREGADOR
(
	ID_ENTREGADOR	INT				IDENTITY,
	NOME			VARCHAR(40)		NOT NULL,
	TELEFONE		VARCHAR(15)		NOT NULL,
	ID_PEDIDO		INT				
	
	CONSTRAINT	PK_TB_ENTREGADOR_ID_ENTREGADOR	   PRIMARY KEY (ID_ENTREGADOR),
	CONSTRAINT	FK_TB_ENTREGADOR_ID_PEDIDO  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
)
GO